FROM nginx:1.15.0-alpine

# Substituir o arquivo de configuração do nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

#Cria a pasta, se nao existir e também cria um arquivo php lá.
RUN mkdir /var/www/html -p && touch /var/www/html/index.php




